# Generated by Django 4.0.1 on 2022-01-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApplication', '0004_alter_sanctionedloan_emi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanctionedloan',
            name='approved_loan',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='sanctionedloan',
            name='emi',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='sanctionedloan',
            name='interest',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='sanctionedloan',
            name='is_approved',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='sanctionedloan',
            name='tenure',
            field=models.IntegerField(blank=True),
        ),
    ]
