# Generated by Django 4.0.1 on 2022-01-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApplication', '0005_alter_sanctionedloan_approved_loan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanctionedloan',
            name='approved_loan',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sanctionedloan',
            name='emi',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sanctionedloan',
            name='interest',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sanctionedloan',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sanctionedloan',
            name='tenure',
            field=models.IntegerField(null=True),
        ),
    ]
