# Generated by Django 4.0.1 on 2022-01-20 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
        ('PrevLoan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prevloan',
            name='account_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='prevloan',
            name='amount_paid',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='prevloan',
            name='amount_remaining',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='prevloan',
            name='bank_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prevloan',
            name='branch_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prevloan',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.customer'),
        ),
        migrations.AlterField(
            model_name='prevloan',
            name='ifsc_code',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='prevloan',
            name='loan_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='prevloan',
            name='loan_tenure',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='prevloan',
            name='loan_type',
            field=models.CharField(choices=[('PERSONAL', 'Personal'), ('VEHICLE', 'Vehicle'), ('HOME', 'Home')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prevloan',
            name='micr_code',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
