# Generated by Django 4.0.1 on 2022-01-21 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrevLoan', '0002_alter_prevloan_account_no_alter_prevloan_amount_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prevloan',
            name='amount_remaining',
        ),
    ]
